info:
  project:
    name: Spring Cloud Start
    version: 0.3.1
# remember to update static/install.sh as well:
  spring-boot:
    version: 1.2.1.RELEASE

cloud:
  groupId: org.springframework.cloud
  artifactId: spring-cloud-starter
  versions:
    - name : Latest SNAPSHOT
      id: 1.0.0.BUILD-SNAPSHOT
      default: false
    - name: 1.0.0.RC3
      id: 1.0.0.RC3
      default: true
  dependencies:
    - name: Cloud
      content:
        - name: Eureka
          id: cloud-eureka
          description: Support for spring-cloud-netflix Eureka
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-eureka
        - name: Eureka Server
          id: cloud-eureka-server
          description: Support for spring-cloud-netflix Eureka Server
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-eureka-server
        - name: AWS
          id: cloud-aws
          description: Support for spring-cloud-aws
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-aws
        - name: Feign
          id: cloud-feign
          description: Support for spring-cloud-netflix Feign
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-feign
        - name: Hystrix
          id: cloud-hystrix
          description: Support for spring-cloud-netflix Hystrix
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-hystrix
        - name: Hystrix Dashboard
          id: cloud-hystrix-dashboard
          description: Support for spring-cloud-netflix Hystrix Dashboard
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-hystrix-dashboard
        - name: OAuth2
          id: cloud-oauth2
          description: Support for spring-cloud-security OAuth2
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-oauth2
        - name: Ribbon
          id: cloud-ribbon
          description: Support for spring-cloud-netflix Ribbon
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-ribbon
        - name: Turbine
          id: cloud-turbine
          description: Support for spring-cloud-netflix Turbine
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-turbine
        - name: Turbine AMQP
          id: cloud-turbine-amqp
          description: Support for spring-cloud-netflix Turbine AMQP
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-turbine-amqp
        - name: Zuul
          id: cloud-zuul
          description: Support for spring-cloud-netflix Zuul
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-zuul
        - name: AWS JDBC
          id: cloud-aws-jdbc
          description: Support for spring-cloud-aws-jdbc
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-aws-jdbc
        - name: AWS Messaging
          id: cloud-aws-messaging
          description: Support for spring-cloud-aws-messaging
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-aws-messaging
        - name: Cloud Bus AMQP
          id: cloud-bus-amqp
          description: Support for spring-cloud-bus-amqp
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-bus-amqp
        - name: Cloud Security
          id: cloud-security
          description: Support for spring-cloud-security
          groupId: ${cloud.groupId}
          artifactId: ${cloud.artifactId}-security
  bootVersions:
    - name: 1.2.1
      id: 1.2.1.RELEASE
      cloudVersionRange: 1.0.0.RC3
      default: true

